### PR TITLE
Created entities, added mapping.

### PR DESCRIPTION
**Pull request by kmusienko**

### CODE REVIEW

**Comment by khdimon** [comment]
It may be necessary to add fields users and groups to the entity Location?

**Comment by kmusienko** [comment]
@thedikiy, maybe you are right. But @svoronin has already approved database schema where phone, contact links etc are separate tables.

**Comment by khdimon** [comment]
@thedikiy, I push "approve" but maybe too early, how do you think, can I Merge?

**Comment by thedikiy** [comment]
@khdimon Yes, i think we can start with this and discuss changes later

**Comment by svoronin** [comment]
I'm pretty flexible on those schema changes. So thanks for going ahead and merging these changes

**Pull request merged**
